ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.home, name="ShopHome"),
    path('about/', views.about, name="AboutUS"),
    path('contact', views.contact, name="Contactus"),
    path('tracker/', views.tracker, name="Trackingstatus"),
    path('search/', views.search, name="Search"),
    path('productview/<int:id>', views.productview, name="prodview"),
    path('checkout/', views.checkout, name="Checkout"),
    path('sell/', views.SellView.as_view(), name="Sell")
]

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default="")
    subcategory = models.CharField(max_length=50, default="")
    price = models.IntegerField(default=0)
    desc = models.CharField(max_length=300)
    pub_date = models.DateTimeField()
    img = models.ImageField(upload_to='product_images', default="")

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('shop:prodview', kwargs={'id': self.id})


class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50, default="")
    email = models.EmailField(max_length=50, default="")
    phone = models.CharField(max_length=20, default="")
    desc = models.CharField(max_length=500, default="")

    def __str__(self):
        return self.name


class Order(models.Model):
    ord_id = models.AutoField(primary_key=True)
    item_json = models.CharField(max_length=5000, default="")
    name = models.CharField(max_length=50, default="")
    email = models.EmailField(max_length=50, default="")
    phone = models.CharField(max_length=20, default="")
    address1 = models.CharField(max_length=300, default="")
    address2 = models.CharField(max_length=300, default="")
    city = models.CharField(max_length=300, default="")
    state = models.CharField(max_length=300, default="")
    zip_code = models.CharField(max_length=30, default="")


class OrderUpdate(models.Model):
    update_id = models.AutoField(primary_key=True)
    order_id = models.IntegerField(default=0)
    update_desc = models.CharField(max_length=5000)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.update_desc[0:7] + "..."

ecommerce/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    return render(request, 'base.html')

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product, Contact, Order, OrderUpdate
from math import ceil
import json
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView


# Create your views here.

def home(request):
    products = Product.objects.all()
    n = len(products)
    allprods = []
    catprods = Product.objects.values('category', 'id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prod = Product.objects.filter(category=cat)
        n = len(prod)
        nslides = n // 4 + ceil(n / 4 - n // 4)
        allprods.append([prod, range(1, nslides), nslides])

    params = {'allprods': allprods}
    return render(request, 'shop/home.html', params)


def searchMatch(query, item):
    query = query.lower()
    if query in item.desc.lower() or query in item.product_name.lower() or query in item.category.lower():
        return True
    return False


def search(request):
    query = request.GET.get('search')
    allprods = []
    catprods = Product.objects.values('category', 'id')
    cats = {item['category'] for item in catprods}
    for cat in cats:
        prodtemp = Product.objects.filter(category=cat)
        prod = [item for item in prodtemp if searchMatch(query, item)]
        n = len(prod)
        nslides = n // 4 + ceil(n / 4 - n // 4)
        if len(prod) != 0:
            allprods.append([prod, range(1, nslides), nslides])

    params = {'allprods': allprods, 'msg': ""}
    if len(allprods) == 0 or len(query) < 3:
        params['msg'] = "Please make sure to enter a relevent search item"
    return render(request, 'shop/Search.html', params)


def about(request):
    return render(request, 'shop/about.html')


def tracker(request):
    if request.method == "POST":
        orderid = request.POST.get('orderid', '')
        email = request.POST.get('email', '')
        try:
            order = Order.objects.filter(ord_id=orderid, email=email)
            if len(order) > 0:
                update = OrderUpdate.objects.filter(order_id=orderid)
                updates = []
                for item in update:
                    updates.append(
                        {'text': item.update_desc, 'time': item.timestamp})
                    response = json.dumps({"status": "success", "updates": updates, "itemsJson": order[0].item_json},
                                          default=str)
                return HttpResponse(response)
            else:
                return HttpResponse('{"status":"noitem"}')
        except Exception as e:
            return HttpResponse('{"status":"error"}')

    return render(request, 'shop/tracker.html')


def productview(request, id):
    product = Product.objects.filter(id=id)
    return render(request, 'shop/productview.html', {'product': product[0]})


def checkout(request):
    thank = False
    if request.method == "POST":
        itemsJson = request.POST.get('itemsJson', '')
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        address1 = request.POST.get('address1', '')
        address2 = request.POST.get('address2', '')
        zipcode = request.POST.get('zipcode', '')
        city = request.POST.get('city', '')
        state = request.POST.get('state', '')
        order = Order(item_json=itemsJson, name=name, email=email, phone=phone,
                      address1=address1, address2=address2, city=city, state=state, zip_code=zipcode)
        order.save()
        update = OrderUpdate(order_id=order.ord_id,
                             update_desc="The order has been placed")
        update.save()
        ord_id = order.ord_id
        thank = True
        return render(request, 'shop/checkout.html', {"thank": thank, "id": ord_id})
    return render(request, 'shop/checkout.html')


def contact(request):
    if request.method == "POST":
        name = request.POST.get('name', '')
        email = request.POST.get('email', '')
        phone = request.POST.get('phone', '')
        desc = request.POST.get('desc', '')
        contactus = Contact(name=name, email=email, phone=phone, desc=desc)
        contactus.save()
    return render(request, 'shop/contact.html')


class SellView(CreateView):
    model = Product
    template_name = 'shop/sell.html'
    fields = ['product_name', 'category', 'subcategory', 'price', 'desc', 'pub_date', 'img']
    slug_field = 'id'
    slug_url_kwarg = 'id'

    def form_valid(self, form):
        if 'img' in self.request.FILES:
            form.instance.thumbnail = self.request.FILES['img']
        return super().form_valid(form)

shop/templates/shop/Search.html
{%extends 'shop/base.html'%}
{%load static%}
{%block title%}Search Results{%endblock%}
{%block css%}
<style>
.col-md-3 {
    display: inline-block;
    margin-left: -4px;
}

.carousel-indicators .active {
    background-color: blue;
}

.col-md-3 img {
    width: 220px;
    height: 200px;
}

body .carousel-indicator li {
    background-color: blue;
}

body .carousel-indicators {
    bottom: 0;
}

body .carousel-control-prev-icon,
body .carousel-control-next-icon {
    background-color: blue;
}

body .no-padding {
    padding-left: 0,
        padding-right: 0;
}

.carousel-control-prev,
.carousel-control-next {
    top: auto;
    bottom: auto;
    padding-top: 200px;
}

h1,
h2,
h3,
h4,
h5,
h6 {
    margin-top: 20px;
    margin-bottom: .5rem;
    margin-left: 50px;
}
</style>
{%endblock%}
{%block body%}
<div class="container">
    {%for product, range, nslides in allprods%}
    <h5 class=" my5 ">{{product.0.category}}</h5>
    <div class="row">
        <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
            <ul class="carousel-indicators ">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                {%for i in range%}
                <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
                {%endfor%}
            </ul>
            <div class="container carousel-inner no-padding">
                <div class="carousel-item active">
                    {%for prod in product%}
                    <div class="col-xs-3 col-sm-3 col-md-3">
                        <div class="card align-items-center" style="width: 18rem;">
                            <img src="{{prod.img.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title" id="namepr{{prod.id}}">{{prod.product_name}}</h5>
                                <p class="card-text"><b id = "pricepr{{prod.id}}">Rs.{{prod.price}}</b></p>
                                <p class="card-text">{{prod.desc|slice:"0:23"}}...</p>
                                <a href="{%url 'shop:prodview' prod.id%}" class="btn btn-primary">View</a>
                                <span id="divpr{{prod.id}}" class="divpr">
                                    <button id="pr{{prod.id}}" class="btn btn-primary cart">Add to cart</button>
                                </span>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last%}
                </div>
                <div class="carousel-item">
                    {%endif%}
                    {%endfor%}
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
    {%endfor%}
</div>
{%endblock%}
{%block js%}
<script>
{%if msg|length != 0%}
alert('{{msg}}');
window.location.href = "/";
{%endif%}
if (localStorage.getItem('cart') == null) {
    var cart = {};
} else {
    cart = JSON.parse(localStorage.getItem('cart'));
    updateCart(cart);
}

function updatePopover(cart) {
    let popStr = "";
    popStr = popStr + "<h5> Items in your cart </h5> <div class = 'my-2 mx-2'>";

    let i = 1;
    for (var item in cart) {
        if(cart[item][0]!=0)
        {popStr += `<b>${i}. </b> ${document.getElementById("name" + item).innerHTML.slice(0,19)}...   Qty: ${cart[item][0]}<br>`
        i = i + 1;}
    }
    popStr += "</div>"
    popStr += "<a href='{%url 'shop:Checkout'%}' class='btn btn-primary' id = 'checkout'>Checkout</a>"
    document.getElementById("popcart").setAttribute('data-content', popStr);
    $('#popcart').popover('show');
}

function updateCart(cart) {

    var total = 0;
    for (var item in cart) {
        total += cart[item][0];
        if (cart[item][0] != 0) { document.getElementById('div' + item).innerHTML = `<button id ="minus${item}" class="btn btn-primary minus">-</button>
        <span id ="val${item}">${cart[item][0]}</span> <button id = "plus${item}" class = "btn btn-primary plus">+</button>
        ` } else {
            document.getElementById('div' + item).innerHTML = `<button id="${item}" class="btn btn-primary cart">Add to cart</button>`
        }
    }

    localStorage.setItem('cart', JSON.stringify(cart));
    updatePopover(cart);
    document.getElementById('cart').innerHTML = total;



}

function clearCart() {
    cart = JSON.parse(localStorage.getItem('cart'));
    for (var item in cart) {
        document.getElementById('div' + item).innerHTML = `<button id="${item}" class="btn btn-primary cart">Add to cart</button>`
    }
    localStorage.clear();
}
//when plus or minus button is clicked
$('.divpr').on("click", "button.minus", function() {
    var a = this.id.slice(5, );
    console.log(a);
    cart[a][0] = cart[a][0] - 1;
    cart[a][0] = Math.max(0, cart[a][0]);
    updateCart(cart);
    if (cart[a][0] != 0)
        document.getElementById('val' + a).innerHTML = cart[a][0];


});
$('.divpr').on("click", "button.plus", function() {

    var a = this.id.slice(4, );
    cart[a][0] = cart[a][0] + 1;
    updateCart(cart);
    document.getElementById('val' + a).innerHTML = cart[a][0];

});
$('.divpr').on("click", "button.cart", function() {
    var idstr = this.id.toString();
    if (cart[idstr] != undefined) {
        cart[idstr][0] = cart[idstr][0]+1;
    } else {
        var qty = 1;
        var name = document.getElementById('name'+idstr).innerHTML;
        var price = document.getElementById('price'+idstr).innerHTML.slice(3,);
        cart[idstr] = [qty,name,price];
    }
    updateCart(cart);

});
</script>
{%endblock%}

shop/templates/shop/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <title>{% block title %} {% endblock %}</title>
</head>
{%block css%} {%endblock%}

<body>
    {%load static%}
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:black">
        <a class="navbar-brand" href="{%url 'shop:ShopHome'%}">E-commerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{%url 'shop:ShopHome'%}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{%url 'shop:AboutUS'%}">About</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{%url 'shop:Trackingstatus'%}">Track</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{%url 'shop:Contactus'%}">ContactUS</a>
                </li>
                 <li class="nav-item active">
                    <a class="nav-link" href="{%url 'shop:Sell'%}">Sell</a>
                </li>
            </ul>
            <form method = "get" action="{%url 'shop:Search'%}" class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name ="search" id ="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
            <button type="button" class="btn btn-secondary mx-2" id="popcart" data-container="body" data-html="true" data-toggle="popover" data-placement="bottom" data-content=".sscs">
                Cart(<span id="cart">0</span>)
            </button>
        </div>
    </nav>
    {%block body%}
    {%endblock%}
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>

</html>

shop/templates/shop/checkout.html
{%extends 'shop/base.html'%}
{%block title%} Checkout {%endblock%}
{%block body%}
<div class="container">
    <div class="col my-2">
        <h2> Step1 - Check your order</h2>
        <div class="my-4">
            <ul class="list-group" id="items">
            </ul>
        </div>
    </div>
    <div class="col">
        <h2>Step-2 Enter Details</h2>
        <form action="{%url 'shop:Checkout'%}" method="post">
            {% csrf_token %}
            <input type="hidden" id="itemsJson" name="itemsJson">
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="email" name="email">
                </div>
                <div class="form-group col-md-6">
                    <label for="name">Name</label>
                    <input type="name" class="form-control" id="name" name="name">
                </div>
            </div>
            <div class="form-group">
                <label for="inputAddress">Address</label>
                <input type="text" class="form-control" id="address1" name="address1" placeholder="Enter Address">
            </div>
            <div class="form-group">
                <label for="inputAddress2">Address 2</label>
                <input type="text" class="form-control" id="address2" name="address2" placeholder="Enter Address">
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputCity">City</label>
                    <input type="text" class="form-control" id="city" name="city">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputState">State</label>
                    <input type="text" class="form-control" id="state" name="state" placeholder="Enter State">
                </div>
                <div class="form-group col-md-2">
                    <label for="inputZip">Zip</label>
                    <input type="text" class="form-control" id="zipcode" name="zipcode">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPhone">Phone Number</label>
                <input type="tel" class="form-control" id="phone" name="phone">
            </div>
            <button type="submit" class="btn btn-primary">Place order</button>
        </form>
    </div>
</div>
{%endblock%}
{% block js %}
<script>
let sum = 0;
if (localStorage.getItem('cart') == null) {
    var cart = {};
} else {
    cart = JSON.parse(localStorage.getItem('cart'));

}
if ($.isEmptyObject(cart)) {
    let mystr = `<p> Your cart is empty </p>`
    $('#items').append(mystr);

} else {
    var bill = 0;
    for (item in cart) {
        if(cart[item][0]!=0)
        {sum += cart[item][0];
        bill +=cart[item][0]*parseInt(cart[item][2]);
        let mystr = ` <li class="list-group-item d-flex justify-content-between align-items-center">
                    ${cart[item][1]}
                    <span class="badge badge-primary badge-pill">Rs.${cart[item][0]} X ${cart[item][2]}</span>
                </li>`
        $('#items').append(mystr);}
    }
    
    
   let mystr = ` <li class="list-group-item d-flex justify-content-between align-items-center my-2">
                    <b>Total amount to be paid</b>
                    <span class="badge badge-primary badge-pill"><b>Rs.${bill}</b></span>
                </li>`
    $('#items').append(mystr);

}
document.getElementById('cart').innerHTML = sum;
$('#itemsJson').val(JSON.stringify(cart));
{%if thank%}
alert('thanks for ordering Your tracking id is {{id}}');
localStorage.clear(); 
document.location ="/";
{%endif%}
</script>
{% endblock %}

shop/templates/shop/contact.html
{%extends 'shop/base.html'%}
{%block title%} Contact {%endblock%}
{%block body%}
<div class="container my-2">
    <h1>Contact us</h1>
    <form action="{%url 'shop:Contactus'%}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name='name' placeholder="Enter your name">
        </div>
        <div class="form-group">
            <label for="name">Email</label>
            <input type="email" class="form-control" id="email" name='email' placeholder="Enter your Email">
        </div>
        <div class="form-group">
            <label for="name">Phone</label>
            <input type="tel" class="form-control" id="phone" name='phone' placeholder="Enter your Phone Number">
        </div>
        <div class="form-group">
            <label for="desc">how may we help you?</label>
            <textarea class="form-control" id="desc" name="desc" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{%endblock%}

shop/templates/shop/home.html
{%extends 'shop/base.html'%}
{%load static%}
{%block title%} E-commerce {%endblock%}
{%block css%}
<style>
.col-md-3 {
    display: inline-block;
    margin-left: -4px;
}

.carousel-indicators .active {
    background-color: blue;
}

.col-md-3 img {
    width: 220px;
    height: 200px;
}

body .carousel-indicator li {
    background-color: blue;
}

body .carousel-indicators {
    bottom: 0;
}

body .carousel-control-prev-icon,
body .carousel-control-next-icon {
    background-color: blue;
}

body .no-padding {
    padding-left: 0,
        padding-right: 0;
}

.carousel-control-prev,
.carousel-control-next {
    top: auto;
    bottom: auto;
    padding-top: 200px;
}

h1,
h2,
h3,
h4,
h5,
h6 {
    margin-top: 20px;
    margin-bottom: .5rem;
    margin-left: 50px;
}
</style>
{%endblock%}
{%block body%}
<div class="container">
    {%for product, range, nslides in allprods%}
    <h5 class=" my5 ">{{product.0.category}}</h5>
    <div class="row">
        <div id="demo{{forloop.counter}}" class="col carousel slide my-3" data-ride="carousel">
            <ul class="carousel-indicators ">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                {%for i in range%}
                <li data-target="#demo{{forloop.parentloop.counter}}" data-slide-to="{{i}}"></li>
                {%endfor%}
            </ul>
            <div class="container carousel-inner no-padding">
                <div class="carousel-item active">
                    {%for prod in product%}
                    <div class="col-xs-3 col-sm-3 col-md-3">
                        <div class="card align-items-center" style="width: 18rem;">
                            <img src="{{prod.img.url}}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <h5 class="card-title" id="namepr{{prod.id}}">{{prod.product_name}}</h5>
                                <p class="card-text"><b id = "pricepr{{prod.id}}">Rs.{{prod.price}}</b></p> 
                                <p class="card-text">{{prod.desc|slice:"0:23"}}...</p>
                                <a href="{%url 'shop:prodview' prod.id%}" class="btn btn-primary">View</a>
                                <span id="divpr{{prod.id}}" class="divpr">
                                    <button id="pr{{prod.id}}" class="btn btn-primary cart">Add to cart</button>
                                </span>
                            </div>
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:4 and forloop.counter > 0 and not forloop.last%}
                </div>
                <div class="carousel-item">
                    {%endif%}
                    {%endfor%}
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#demo{{forloop.counter}}" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo{{forloop.counter}}" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
    {%endfor%}
</div>
{%endblock%}
{%block js%}
<script>
if (localStorage.getItem('cart') == null) {
    var cart = {};
} else {
    cart = JSON.parse(localStorage.getItem('cart'));
    updateCart(cart);
}

function updatePopover(cart) {
    let popStr = "";
    popStr = popStr + "<h5> Items in your cart </h5> <div class = 'my-2 mx-2'>";

    let i = 1;
    for (var item in cart) {
        if(cart[item][0]!=0)
        {popStr += `<b>${i}. </b> ${document.getElementById("name" + item).innerHTML.slice(0,19)}...   Qty: ${cart[item][0]}<br>`
        i = i + 1;}
    }
    popStr += "</div>"
    popStr += "<a href='{%url 'shop:Checkout'%}' class='btn btn-primary' id = 'checkout'>Checkout</a>"
    document.getElementById("popcart").setAttribute('data-content', popStr);
    $('#popcart').popover('show');
}

function updateCart(cart) {

    var total = 0;
    for (var item in cart) {
        total += cart[item][0];
        if (cart[item][0] != 0) { document.getElementById('div' + item).innerHTML = `<button id ="minus${item}" class="btn btn-primary minus">-</button>
        <span id ="val${item}">${cart[item][0]}</span> <button id = "plus${item}" class = "btn btn-primary plus">+</button>
        ` } else {
            document.getElementById('div' + item).innerHTML = `<button id="${item}" class="btn btn-primary cart">Add to cart</button>`
        }
    }

    localStorage.setItem('cart', JSON.stringify(cart));
    updatePopover(cart);
    document.getElementById('cart').innerHTML = total;



}

function clearCart() {
    cart = JSON.parse(localStorage.getItem('cart'));
    for (var item in cart) {
        document.getElementById('div' + item).innerHTML = `<button id="${item}" class="btn btn-primary cart">Add to cart</button>`
    }
    localStorage.clear();
}
//when plus or minus button is clicked
$('.divpr').on("click", "button.minus", function() {
    var a = this.id.slice(5, );
    console.log(a);
    cart[a][0] = cart[a][0] - 1;
    cart[a][0] = Math.max(0, cart[a][0]);
    updateCart(cart);
    if (cart[a][0] != 0)
        document.getElementById('val' + a).innerHTML = cart[a][0];


});
$('.divpr').on("click", "button.plus", function() {

    var a = this.id.slice(4, );
    cart[a][0] = cart[a][0] + 1;
    updateCart(cart);
    document.getElementById('val' + a).innerHTML = cart[a][0];

});
$('.divpr').on("click", "button.cart", function() {
    var idstr = this.id.toString();
    if (cart[idstr] != undefined) {
        cart[idstr][0] = cart[idstr][0]+1;
    } else {
        var qty = 1;
        var name = document.getElementById('name'+idstr).innerHTML;
        var price = document.getElementById('price'+idstr).innerHTML.slice(3,);
        cart[idstr] = [qty,name,price];
    }
    updateCart(cart);

});
</script>
{%endblock%}